In [ ]:
import nestsmart.Asset

In [ ]:
import numpy as np
import xarray as xr

In [ ]:
from icecream import ic

In [ ]:
import nestsmart.utils

In [ ]:
nestsmart.utils.uqpy_wrapper_balances_eop(input=np.array([1,2]))

In [1]:
from UQpy.sampling import MonteCarloSampling
from UQpy.run_model.RunModel import RunModel
from UQpy.run_model.model_execution.PythonModel import PythonModel
from UQpy.distributions import Normal
import time
import numpy as np

In [2]:
pick_model = 'all'

In [3]:
if pick_model in {'scalar', 'vector', 'all'}:
    d = Normal(loc=0.05, scale=0.174)
    x_mcs = MonteCarloSampling(distributions=[d, d, d], nsamples=5, random_state=987979)
    names = ['var1', 'var11', 'var111']

    # UQpy returns samples as an ndarray
    print("Monte Carlo samples of three random variables from a standard normal distribution.")
    print('Samples stored as an array:')
    print('Data type:', type(x_mcs.samples))
    print('Number of samples:', len(x_mcs.samples))
    print('Dimensions of samples:', np.shape(x_mcs.samples))
    print('Samples')
    print(x_mcs.samples)

Monte Carlo samples of three random variables from a standard normal distribution.
Samples stored as an array:
Data type: <class 'numpy.ndarray'>
Number of samples: 5
Dimensions of samples: (5, 3)
Samples
[[ 0.43832705 -0.06167016 -0.01707987]
 [ 0.46626645  0.09084551  0.20504189]
 [ 0.00286666  0.16527559 -0.23927488]
 [ 0.07013848  0.03357816  0.23254389]
 [ 0.05578059  0.03377758 -0.02950358]]


In [4]:
if pick_model in {'vector', 'all'}:
    x_mcs_tri = x_mcs.samples.reshape(5, 1, 3)
    x_mcs_tri_list = list(x_mcs_tri)

    print("Monte Carlo samples of three random variables from a standard normal distribution.")
    print('Samples stored as an array:')
    print('Data type:', type(x_mcs_tri))
    print('Number of samples:', len(x_mcs_tri))
    print('Dimensions of samples:', np.shape(x_mcs_tri))
    print('Samples')
    print(x_mcs_tri)

Monte Carlo samples of three random variables from a standard normal distribution.
Samples stored as an array:
Data type: <class 'numpy.ndarray'>
Number of samples: 5
Dimensions of samples: (5, 1, 3)
Samples
[[[ 0.43832705 -0.06167016 -0.01707987]]

 [[ 0.46626645  0.09084551  0.20504189]]

 [[ 0.00286666  0.16527559 -0.23927488]]

 [[ 0.07013848  0.03357816  0.23254389]]

 [[ 0.05578059  0.03377758 -0.02950358]]]


In [5]:
if pick_model in {'scalar', 'all'}:
    # Call to RunModel - Here we run the model while instantiating the RunModel object.
    t = time.time()
    m = PythonModel(model_script='utils.py', model_object_name='uqpy_wrapper_balances_eop')
    m11 = RunModel(model=m, ntasks=1 )
    m11.run(samples=x_mcs.samples,)
    t_ser_python = time.time() - t
    print("\nTime for serial execution:")
    print(t_ser_python)
    print()
    print("The values returned from the Matlab simulation:")
    print(m11.qoi_list)

ic| returns: array([ 0.43832705, -0.06167016, -0.01707987])
ic| returns: array([0.46626645, 0.09084551, 0.20504189])
ic| returns: array([ 0.00286666,  0.16527559, -0.23927488])
ic| returns: array([0.07013848, 0.03357816, 0.23254389])
ic| returns: array([ 0.05578059,  0.03377758, -0.02950358])



Time for serial execution:
1.7476608753204346

The values returned from the Matlab simulation:
[<xarray.DataArray (year: 4)>
array([100.        , 143.83270516, 134.96251942, 132.65737674])
Coordinates:
  * year     (year) int64 2000 2001 2002 2003, <xarray.DataArray (year: 4)>
array([100.        , 146.62664498, 159.94701668, 192.74285462])
Coordinates:
  * year     (year) int64 2000 2001 2002 2003, <xarray.DataArray (year: 4)>
array([100.        , 100.28666646, 116.86160463,  88.89955776])
Coordinates:
  * year     (year) int64 2000 2001 2002 2003, <xarray.DataArray (year: 4)>
array([100.        , 107.01384817, 110.60717588, 136.32819831])
Coordinates:
  * year     (year) int64 2000 2001 2002 2003, <xarray.DataArray (year: 4)>
array([100.        , 105.57805868, 109.14423022, 105.92408458])
Coordinates:
  * year     (year) int64 2000 2001 2002 2003]


In [ ]:
if pick_model in {'vector', 'all'}:
    # Call to RunModel - Here we run the model while instantiating the RunModel object.
    t = time.time()
    m = PythonModel(model_script='utils.py', model_object_name='uqpy_wrapper_balances_eop')
    m21 = RunModel(samples=x_mcs_tri, ntasks=1,  model=m)
    t_ser_python = time.time() - t
    print("\nTime for serial execution:")
    print(t_ser_python)
    print()
    print("The values returned from the Matlab simulation:")
    print(m21.qoi_list)

In [10]:
m11.qoi_list[4]

<xarray.DataArray (year: 4)>
array([100.        , 105.57805868, 109.14423022, 105.92408458])
Coordinates:
  * year     (year) int64 2000 2001 2002 2003